FROM openjdk:17-jdk-alpine3.13

COPY target/java-spring-0.0.1-SNAPSHOT.jar java-spring-1.0.0.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/java-spring-1.0.0.jar"]

ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD